### PR TITLE
Fix #579 (piral-ng destroying all modules instead of only the intended one)

### LINKED ISSUE #579: [piral-ng] When one Angular module is unloaded, all other modules are incorrectly torn down as well
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Reproducible with:
```
piral-core and piral-ng: 0.15.5 (any 0.15 version should do).
OS: tested on Win10 and Linux Mint
Browser: tested with latest Edge and Firefox 
```

## Description and steps to reproduce

**Scenario:**
There is an Angular pilet using `piral-ng` that provides components from different modules all defined using `defineNgModule`.
For easy reproducibility load one extension from each module into the shell.

1. Perform an action that unloads one of the extension slots.
2. piral-ng will not only correctly destroy that component and the now unused module, *but also all other Angular modules loaded via piral-ng*.
3. The other extension slot's DOM will be empty, since the Angular component got wrongly unloaded.
4. Trying to unload that other extension as well, will result in a hard React crash, since React still thinks that the component is loaded.

## Expected behavior

When all components of an Angular module go out of scope, only that module should be unloaded.

## Actual behavior

All Angular modules and components will be unloaded/unmounted.

## Analysis

This is the code called when a piral-ng component is to be unmounted:

https://github.com/smapiot/piral/blob/143d72e29e0d095ec26023fb1bd83528f07b2b28/src/converters/piral-ng/src/module.ts#L74-L85

This method correctly tries to tear down the module if no other component instances of that module are left.

The `teardown` method looks like this:

https://github.com/smapiot/piral/blob/143d72e29e0d095ec26023fb1bd83528f07b2b28/src/converters/piral-ng/src/startup.ts#L55-L66

The code tries to unload the platform of the currently running module, which is also technically correct.

But what are the platforms used?

https://github.com/smapiot/piral/blob/143d72e29e0d095ec26023fb1bd83528f07b2b28/src/converters/piral-ng/src/startup.ts#L16-L21

They are `platformBrowserDynamic` platforms which looks ok at first too.

**However,** looking at Angular's implementation reveals the following:

https://github.com/angular/angular/blob/2fc5b70fcedb8ac35b825b245c0ae394dc125244/packages/platform-browser-dynamic/src/platform-browser-dynamic.ts#L33-L34

https://github.com/angular/angular/blob/2fc5b70fcedb8ac35b825b245c0ae394dc125244/packages/core/src/application_ref.ts#L272-L293

Looking closely at this, you'll notice that **`platformBrowserDynamic` by default always returns the same instance!**
That means that destroying the platform of one module, you'll destroy the platform of all modules, actually destroying every Angular component and module that's loaded.

### 1. The easy but dumb solution

Let everything just run on a single platform and don't destroy it.
This has a lot of bad implications for performance and sandboxing of the pilets and probably isn't really worth much.

### 2. The intended way

From looking at the code, I can guess that it was intended for every module to run on its own platform.
With the help of a bunch of Angular internals (namely `ALLOW_MULTIPLE_PLATFORMS` as seen above) one can enable multi-platform  behavior for the platform factory.

Since I've already gotten all the way there, I'm going to submit a pull request for this solution shortly.

### PR DESCRIPTION
**Pull request by Siphalor**
## Prerequisites

Please make sure you can check the following boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [x] All new and existing tests passed

### Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ ] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes

### Description

Implements the second solution as outlined in #579.

It makes use of some Angular internals similarly to how Angular does for SSR: https://github.com/angular/angular/blob/main/packages/platform-server/src/server.ts

### Remarks

My Angular knowledge is limited, but I tried my best at analyzing the issue and this solution.
Let me know if I've missed anything.

While relying on Angular internals is hacky, I don't really think there's a better fix for this issue.

Thanks for the great work on this framework :D

### CODE REVIEW

File: src/converters/piral-ng/src/startup.ts [hunk 1]
```diff
@@ -11,11 +21,19 @@ function getVersionHandler(versions: Record<string, () => void>) {
...
+    provide: ALLOW_MULTIPLE_PLATFORMS,
+    useValue: true,
+  },
+]);
 const runningModules: Array<[any, NgModuleInt, PlatformRef]> = [];
 
 function startNew(BootstrapModule: any, context: ComponentContext, ngOptions?: NgOptions) {
   const path = context.publicPath || '/';
-  const platform = platformBrowserDynamic([
+  const platform = customPlatformDynamicFactory([
```
Comment (FlorianRappl) [inline src/converters/piral-ng/src/startup.ts:36]: This is awesome - the only question I have is regarding in what version(s) of Angular this is available?

We'd accept it anyway, but if this is not available, e.g., in Angular 6 or lower then we'd need to document this (and make clear that `piral-ng` only works for Angular 7+).

Comment (Siphalor) [reply src/converters/piral-ng/src/startup.ts:36]: That's a good point.

From looking at the git blame all the methods and tokens used stem from mid 2016 (https://github.com/angular/angular/commit/979657989bab4fb93faf6a207d30760faa9bd696) and the 4.0.0-betas in February 2017 (https://github.com/angular/angular/commit/17486fd696a49fd2d11fe295ec5add8bb44fb398).

So I think this should be fine :)

**Review by FlorianRappl — APPROVED** [review]
